#docker env variables
TIMEZONE=America/New_York
PUID=568
PGID=568
CONFIG_PATH=/configs
TV_PATH=/media/tv
MOVIES_PATH=/media/movies
DOWNLOADS_PATH=/media/downloads

version: "2.1"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    user: apps:apps
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${TV_PATH}:/media/tv
      - ${MOVIES_PATH}:/media/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
    networks:
      - arr
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - arr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
      - JELLYFIN_TYPE=emby
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - arr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
      - "8118:8118"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - PRIVOXY_ENABLED=false
    volumes:
      - ${CONFIG_PATH}/qbit:/config
      - ${DOWNLOADS_PATH}:/media/downloads
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - arr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIES_PATH}:/media/movies 
      - ${DOWNLOADS_PATH}:/media/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 568:568
    volumes:
      - ${CONFIG_PATH}/recyclarr:/config
    environment:
      - TZ=${TIMEZONE}
    networks:
      - arr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${TV_PATH}:/media/tv #optional
      - ${DOWNLOADS_PATH}:/media/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr

  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    restart: unless-stopped    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/unpackerr:/config
    networks:
      - arr
    security_opt:
      - no-new-privileges:true

networks:
  arr:
    external: true
