services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 8787:8787
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 8083:8083
    restart: unless-stopped
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 5000:5000
    restart: unless-stopped
